language: php
sudo: false

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

before_script:
  - composer install --dev

script:
  - vendor/phpspec/phpspec/bin/phpspec run -c phpspec.yml -v

matrix:
  allow_failures:
    - php: hhvm
  include:
    - php: 5.6
      env: DEPS="dev"
